version: '3.8'
services:
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./:/varjenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

